default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RORS
  host: localhost
  port: 5432
  username: postgres
  password: Sqlsa!23

test:
  <<: *default
  database: RORS_test
  host: localhost
  port: 5432
  username: postgres
  password: Sqlsa!23

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>